# QuartzPro64 板卡配置
BOARD_NAME="QuartzPro64"
BOARD_SOC="rk3588"
UBOOT_DEFCONFIG="quartzpro64-rk3588_defconfig"
KERNEL_DTB="rk3588-quartzpro64.dtb"
KERNEL_OVERLAYS=""
KERNEL_REPO="https://github.com/armbian/linux-rockchip"
KERNEL_BRANCH="rk-6.1-rkr5.1"
EXTRA_PACKAGES="pciutils,usbutils"
EXTRA_CMDLINE="cma=512M"
