# Orange Pi 5 Plus 板卡配置

BOARD_NAME="Orange Pi 5 Plus"
BOARD_SOC="rk3588"

UBOOT_DEFCONFIG="orangepi-5-plus-rk3588_defconfig"
UBOOT_REPO="https://github.com/u-boot/u-boot"
UBOOT_BRANCH="v2025.07"

KERNEL_DTB="rk3588-orangepi-5-plus.dtb"
KERNEL_OVERLAYS="rockchip-rk3588-panthor-gpu.dtbo"
KERNEL_REPO="https://github.com/armbian/linux-rockchip"
KERNEL_BRANCH="rk-6.1-rkr5.1"
KERNEL_DEFCONFIG="rockchip_linux_defconfig"

# DDR 固件 - 留空让脚本自动搜索
DDR_BIN=""

EXTRA_PACKAGES=""
