Section "Device"
    Identifier  "Mali-G610"
    Driver      "modesetting"
    Option      "AccelMethod"    "none"
EndSection

Section "Screen"
    Identifier  "Default Screen"
    Device      "Mali-G610"
    DefaultDepth 24
EndSection
