# CM3588-NAS 板卡配置
BOARD_NAME="CM3588 NAS"
BOARD_SOC="rk3588"
UBOOT_DEFCONFIG="cm3588-nas-rk3588_defconfig"
KERNEL_DTB="rk3588-cm3588-nas.dtb"
KERNEL_OVERLAYS=""
KERNEL_REPO="https://github.com/armbian/linux-rockchip"
KERNEL_BRANCH="rk-6.1-rkr5.1"
EXTRA_PACKAGES="samba,nfs-common,mdadm,lvm2,pciutils,usbutils"
EXTRA_CMDLINE="cma=512M"
