# ROCK 5 ITX 板卡配置
BOARD_NAME="ROCK 5 ITX"
BOARD_SOC="rk3588"
UBOOT_DEFCONFIG="rock-5-itx-rk3588_defconfig"
KERNEL_DTB="rk3588-rock-5-itx.dtb"
KERNEL_OVERLAYS="rockchip-rk3588-panthor-gpu.dtbo"
KERNEL_REPO="https://github.com/armbian/linux-rockchip"
KERNEL_BRANCH="rk-6.1-rkr5.1"
EXTRA_PACKAGES="pciutils,usbutils,i2c-tools"
EXTRA_CMDLINE="cma=512M"
